<a href="https://colab.research.google.com/github/Viktoria-coder-prog/frontend-learning/blob/main/%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd
import requests
import time
from tqdm import tqdm

**Задача 1. Сбор данных по API**

In [6]:
# формирование запроса
region_code = 76
offset_number = 0
link = f'http://opendata.trudvsem.ru/api/v1/vacancies/region/{region_code}?offset={offset_number}'

In [7]:
# отправка запроса
rqst = requests.get(link)

# подтверждение доступа
rqst.status_code

200

In [12]:
# анализ ответа
rqst.text

'{"status":"200","request":{"api":"v1"},"meta":{"total":4113,"limit":100},"results":{"vacancies":[{"vacancy":{"id":"9c787798-62fb-11f1-8685-7325a21cb113","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1207800166914","email":"s.sokolov@t-ya.ru","hr-agency":false,"inn":"7810909823","kpp":"760401001","name":"ООО \\"ТРАНСПОРТ ЯРОСЛАВИИ\\"","ogrn":"1207800166914","site":"i.fedulova@t-ya.ru","url":"https://trudvsem.ru/company/1207800166914"},"creation-date":"2026-06-08","date_modify":"2026-08-17T13:12:28+0300","salary":"от 57487","salary_min":57487,"salary_max":57487,"job-name":"Слесарь по ремонту автомобилей","vac_url":"https://trudvsem.ru/vacancy/card/1207800166914/9c787798-62fb-11f1-8685-7325a21cb113","employment":"Полная занятость","schedule":"Полный рабочий день","qualification":"Среднее профессиональное образование","requirements":"опыт работы автослесарем; знание технического устройства автобуса умение работать с ручным инструментом, спец. инструментом","duty":"Проводить работы по ремонту автобусов, соблюдая технологические нормы по ремонту и техническому обслуживанию автобусов.","category":{"specialisation":"Транспорт, автобизнес, логистика, склад, ВЭД"},"requirement":{"education":"Общее образование","experience":1},"addresses":{"address":[{"location":"Ярославская область, г Ярославль, Московский проспект, дом: Д. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;","lng":"39.849535","lat":"57.579638"}]},"social_protected":"Инвалид","contact_list":[{"contact_type":"Телефон","contact_value":"+7(910) 973-03-15"},{"contact_type":"Мобильный телефон","contact_value":"+7(910) 973-03-15"}],"contact_person":"Ирина Анатольевна Федулова","work_places":1,"code_profession":"202115","typicalPosition":"Ничего не выбрано","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSocialProtected":["Инвалид"],"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"097dcb68-13b6-11f0-85c2-cb26dff57dd7","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1207800166914","email":"s.sokolov@t-ya.ru","hr-agency":false,"inn":"7810909823","kpp":"760401001","name":"ООО \\"ТРАНСПОРТ ЯРОСЛАВИИ\\"","ogrn":"1207800166914","site":"i.fedulova@t-ya.ru","url":"https://trudvsem.ru/company/1207800166914"},"creation-date":"2025-04-07","date_modify":"2026-08-17T13:12:24+0300","salary":"от 75000","salary_min":75000,"salary_max":100000,"job-name":"Водитель автобуса регулярных городских пассажирских маршрутов (категории М2, М3)","vac_url":"https://trudvsem.ru/vacancy/card/1207800166914/097dcb68-13b6-11f0-85c2-cb26dff57dd7","employment":"Полная занятость","schedule":"Сменная работа","qualification":"Водительское удостоверение кат.D","requirements":"- Водительское удостоверение кат.D - Отсутствие медицинскихпротивопоказаний для работы водителем автобуса -Знание действующих ПДД - Содержание автобуса в соответствии с требованиями технической эксплуатации.","duty":"-Безопаснная перевозка пассажиров по установленным маршрутам городского и пригородного сообщений; - Соблюдение установленного расписания.","category":{"specialisation":"Транспорт, автобизнес, логистика, склад, ВЭД"},"requirement":{"education":"Общее образование","experience":0},"addresses":{"address":[{"location":"Ярославская область, г Ярославль, Московский проспект, дом: ЗД. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;","lng":"39.880878","lat":"57.608323"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(910) 973-03-15"}],"contact_person":"Федулова Ирина Анатольевна","work_places":20,"code_profession":"100817","typicalPosition":"Водитель автобуса на городских маршрутах","skills":[],"workPlaceType":{"workPlaceForeign":true,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":["Только дневная смена"],"conditions":"Вредные","benefit":"Предоставление служебного транспорта","trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"105d5578-2d03-11f1-a71f-0dcd003ac4b5","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1207800166914","email":"s.sokolov@t-ya.ru","hr-agency":false,"inn":"7810909823","kpp":"760401001","name":"ООО \\"ТРАНСПОРТ ЯРОСЛАВИИ\\"","ogrn":"1207800166914","site":"i.fedulova@t-ya.ru","url":"https://trudvsem.ru/company/1207800166914"},"creation-date":"2026-03-31","date_modify":"2026-08-17T13:12:20+0300","salary":"от 54900","salary_min":54900,"salary_max":54900,"job-name":"Слесарь-сантехник (сантехник)","vac_url":"https://trudvsem.ru/vacancy/card/1207800166914/105d5578-2d03-11f1-a71f-0dcd003ac4b5","schedule":"Полный рабочий день","qualification":"Среднее профессиональное образование","requirements":"Начальное профессиональное или среднее профессиональное образование; Умение проводить сантехнические работы.","duty":"Еженедельная чистка ливневой канализации и пожарных гидрантов; Очистка очистных сооружений в летний период; Опрессовка теплотрасс; Ремонт и замена систем теплоснабжения и водоснабжения; Ежегодная подготовка тепловых пунктов и внутренней системы отопления на объектах предприятия.","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Ярославская область, г Ярославль, Московский проспект, дом: Д. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;","lng":"39.880878","lat":"57.608323"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(910) 973-03-15"},{"contact_type":"Эл. почта","contact_value":"oktryar@yandex.ru"}],"contact_person":"Федулоа Ирина Анатольевна ","work_places":1,"code_profession":"104752","typicalPosition":"Слесарь-сантехник (сантехник)","skills":["Ремонт, замена, демонтаж сан-узлов, оборудования сан-узлов","Выполнение работ по ремонту санитарно-технических систем","Монтаж санитарно-технических систем и оборудования","Наладка, регулировка, настройка сантехнических систем","Монтаж, установка сан-узлов, оборудования сан-узлов","Монтаж трубопроводов","Монтаж, устройство, прокладка теплотехнических систем и оборудования","Знать устройство и принцип работы сантехнических систем и оборудования","Знание технологии и техники проведения работ по ремонту систем отопления и горячего водоснабжения","Знание инженерных систем зданий и сооружений","Знать основные виды сантехнических деталей и соединений","Техническое обслуживание, осмотр, эксплуатация сантехнического оборудования","Монтаж трубопроводной арматуры","Замена гибких подводок/подводов","Ремонт, замена, демонтаж смесителей","Монтаж систем канализации/водоотведения","Ремонт, замена, демонтаж сан-узлов, оборудования сан-узлов","Выполнение работ по ремонту санитарно-технических систем","Монтаж санитарно-технических систем и оборудования","Наладка, регулировка, настройка сантехнических систем","Монтаж, установка сан-узлов, оборудования сан-узлов","Монтаж трубопроводов","Монтаж, устройство, прокладка теплотехнических систем и оборудования","Знать устройство и принцип работы сантехнических систем и оборудования","Знание технологии и техники проведения работ по ремонту систем отопления и горячего водоснабжения","Знание инженерных систем зданий и сооружений","Знать основные виды сантехнических деталей и соединений","Техническое обслуживание, осмотр, эксплуатация сантехнического оборудования","Монтаж трубопроводной арматуры","Замена гибких подводок/подводов","Ремонт, замена, демонтаж смесителей","Монтаж систем канализации/водоотведения"],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"hireDate":"2026-03-31T03:00:00+0300","shift":[],"conditions":"Оптимальные","trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"6eced410-2453-11f1-bf4d-d51024d60109","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1207800166914","email":"s.sokolov@t-ya.ru","hr-agency":false,"inn":"7810909823","kpp":"760401001","name":"ООО \\"ТРАНСПОРТ ЯРОСЛАВИИ\\"","ogrn":"1207800166914","site":"i.fedulova@t-ya.ru","url":"https://trudvsem.ru/company/1207800166914"},"creation-date":"2026-03-20","date_modify":"2026-08-17T13:12:18+0300","salary":"от 36000","salary_min":36000,"salary_max":36000,"job-name":"подсобный рабочий","vac_url":"https://trudvsem.ru/vacancy/card/1207800166914/6eced410-2453-11f1-bf4d-d51024d60109","employment":"Полная занятость","schedule":"Неполный рабочий день/неполная рабочая неделя","qualification":"общее среднее образование","requirements":"Ответственность Дисциплинированность","duty":"погрузка-разгрузка товарно-материальных ценностей; перемещение грузов на хранение в складские помещения, распределение их в соответствующие отсеки; поддержание в чистоте производственных помещений, складов и прилегающих у ним территорий; помощь в работе другим сотрудникам предприятии, при наличии соответствующего распоряжения со стороны непосредственного начальника;","category":{"specialisation":"Транспорт, автобизнес, логистика, склад, ВЭД"},"requirement":{"education":"Общее образование","experience":0},"addresses":{"address":[{"location":"Ярославская область, г Ярославль, Московский проспект, дом: ЗД. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;","lng":"39.880878","lat":"57.608323"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(910) 973-03-15"}],"contact_person":"Федулова Ирина Анатольевна","work_places":1,"code_profession":"105152","typicalPosition":"Подсобный рабочий","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":false,"workPlaceQuota":false,"workPlaceSpecial":true},"shift":[],"conditions":"Допустимые","trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"1dcc06bd-802d-11f1-9d9f-7de008f3dac7","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1207800166914","email":"s.sokolov@t-ya.ru","hr-agency":false,"inn":"7810909823","kpp":"760401001","name":"ООО \\"ТРАНСПОРТ ЯРОСЛАВИИ\\"","ogrn":"1207800166914","site":"i.fedulova@t-ya.ru","url":"https://trudvsem.ru/company/1207800166914"},"creation-date":"2026-07-15","date_modify":"2026-08-17T13:12:15+0300","salary":"от 70000","salary_min":70000,"salary_max":80000,"job-name":"Рихтовщик кузовов","vac_url":"https://trudvsem.ru/vacancy/card/1207800166914/1dcc06bd-802d-11f1-9d9f-7de008f3dac7","schedule":"Сменная работа","qualification":"Среднее профессиональное образование","requirements":"-Подтверждённый опыт работы сварщиком ( жестянщиком ). -Аккуратность, ответственность, готовность работать с крупногабаритным транспортом.","duty":"-Выполнение электрогазосварочных работ (основной объём задач); . -Ремонт кузовов автобусов (рихтовка, восстановление металлических и пластиковых элементов); . -освоение и выполнение работ по вклейке стёкол, поможем, научим.","category":{"specialisation":"Транспорт, автобизнес, логистика, склад, ВЭД"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Ярославская область, г Ярославль, Московский проспект, дом: Д. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;","lng":"39.880878","lat":"57.608323"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(910) 973-03-15"},{"contact_type":"Эл. почта","contact_value":"i.fedulova@t-ya.ru"}],"contact_person":"Федулова Ирина Анатольевна","work_places":2,"code_profession":"100933","typicalPosition":"Кузовщик / Рихтовщик","skills":["Сварочные работы","Проведение ремонта","Ответственность\xa0, добросовестность","Саморазвитие, обучаемость","Выполнение планов, задач, поручений и распоряжений","Сварочные работы","Проведение ремонта","Ответственность\xa0, добросовестность","Саморазвитие, обучаемость","Выполнение планов, задач, поручений и распоряжений"],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":["Только ночная смена"],"conditions":"Оптимальные","trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"48d69558-9554-11f1-9253-c35c7c22d563","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1027601123219","email":"adminposh@yarregion.ru","hr-agency":false,"inn":"7624001093","kpp":"762401001","name":"АДМИНИСТРАЦИЯ ПОШЕХОНСКОГО МУНИЦИПАЛЬНОГО ОКРУГА","ogrn":"1027601123219","url":"https://trudvsem.ru/company/1027601123219"},"creation-date":"2026-08-11","date_modify":"2026-08-17T13:09:34+0300","salary":"от 40000","salary_min":40000,"salary_max":50000,"job-name":"Пресс-секретарь","vac_url":"https://trudvsem.ru/vacancy/card/1027601123219/48d69558-9554-11f1-9253-c35c7c22d563","schedule":"Полный рабочий день","qualification":"Журналистика.  Связи с общественностью (PR).  Реклама и маркетинг.   Филология.  Государственное и муниципальное управление","requirements":"владение современными средствами, методами и технологиями работы с информацией и документами; владение информационно-коммуникационными технологиями; умение организовать личный труд и планировать служебное время; владение приемами выстраивания межличностных отношений, ведения деловых переговоров и составления делового письма; владение официально-деловым стилем современного русского языка; соблюдение этики делового общения при взаимодействии с гражданами; разработки нормативных и иных правовых актов по направлению деятельности; организационной работы, подготовки и проведения мероприятий в соответствующей сфере деятельности; системного подхода к решению задач; аналитической, экспертной работы по профилю деятельности; составления и исполнения перспективных и текущих планов; организации взаимодействия со специалистами других органов местного самоуправления (в т.ч. отраслевых и структурных подразделений) для решения профессиональных вопросов; работы с различными источниками информации, систематизации и подготовки аналитических, информационных материалов; ведения служебного документооборота, исполнения служебных документов, подготовки проектов ответов на обращения организаций и граждан; построения межличностных отношений; ведения деловых переговоров; работы с внутренними и периферийными устройствами компьютера; работы с информационно-телекоммуникационными сетями, в том числе сетью Интернет; работы в операционной системе; управления электронной почтой; работы с электронными таблицами; подготовки презентаций; использования графических объектов в электронных документах; работы с базами данных.","duty":"Информационное сопровождение деятельности Главы и Администрации округа, освещение работы в СМИ и на официальном сайте. Взаимодействие со СМИ и общественностью: подготовка и распространение пресс-релизов, официальных заявлений, организация брифингов, пресс-конференций и рабочих встреч. Формирование имиджа: реализация политики в области связей с общественностью, создание положительного имиджа органов местного самоуправления. Мониторинг СМИ и соцсетей: отслеживание публикаций, анализ информационных поводов, подготовка отчетов и информационно-аналитических материалов. Наполнение официального WEB-ресурса: подготовка текстов, обеспечение своевременного обновления информации о деятельности Администрации. Подготовка отчетности: составление квартальных, полугодовых и годовых отчетов о проделанной работе, ответов на официальные запросы и обращения граждан. Организационная работа: планирование мероприятий, сбор, хранение и распространение информационных материалов, подготовка документов для сдачи в архив. Исполнение поручений: выполнение отдельных заданий непосредственного руководителя в рамках компетенции. Соблюдение законодательства: исполнение требований федерального и регионального законодательства, правил внутреннего распорядка, запретов и ограничений для муниципальных служащих, а также норм по защите персональных данных и профилактике коррупции.","category":{"specialisation":"Административная работа, секретариат, АХО"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Ярославская область, Пошехонский район, г Пошехонье, Свободы площадь, дом: Д.9;"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(485) 462-18-64"}],"contact_person":"Красильникова Татьяна Леонидовна","work_places":1,"code_profession":"200036","typicalPosition":"Пресс-секретарь","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"e3c7c270-9a1b-11f1-939b-2796e7afcc16","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1177627012310","email":"iwolga76@yandex.ru","hr-agency":false,"inn":"7612048259","kpp":"761201001","name":"ООО \\"ИВОЛГА\\"","ogrn":"1177627012310","url":"https://trudvsem.ru/company/1177627012310"},"creation-date":"2026-08-17","date_modify":"2026-08-17T13:03:15+0300","salary":"от 30000","salary_min":30000,"salary_max":37000,"job-name":"Продавец продовольственных товаров","vac_url":"https://trudvsem.ru/vacancy/card/1177627012310/e3c7c270-9a1b-11f1-939b-2796e7afcc16","employment":"Полная занятость","schedule":"Сменная работа","qualification":"чётко и вежливо обслуживать покупателей, находить к ним индивидуальный подход, оперативно производить расчёты с покупателями, предотвращать и разрешать конфликтные ситуации","requirements":"чётко и вежливо обслуживать покупателей, находить к ним индивидуальный подход, оперативно производить расчёты с покупателями, предотвращать и разрешать конфликтные ситуации","duty":"Продажа продуктов и обслуживание покупателей. Подготовка товаров к продаже. Организация рабочего места. Размещение товаров по группам, видам и сортам. Подсчет чеков (денежных средств) и их сдача в установленном порядке.","category":{"specialisation":"Продажи, закупки, снабжение, торговля"},"requirement":{"education":"Общее образование","experience":1},"addresses":{"address":[{"location":"Ярославская область, Угличский район, Сосновый поселок, дом: ДОМ 1;"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(905) 133-67-78"},{"contact_type":"Эл. почта","contact_value":"iwolga76@yandex.ru"}],"contact_person":"Виноградова Анна Дмитриевна","work_places":1,"code_profession":"104095","typicalPosition":"Продавец-кассир","skills":[],"addressOffice":"0","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"hireDate":"2026-08-17T03:00:00+0300","shift":["По графику сменности"],"conditions":"Допустимые","trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"6784addc-7aaf-11f1-96a1-71ec6ab38b2c","source":"Вакансия работодателя","region":{"region_code":"7600000000000","name":"Ярославская область"},"company":{"companycode":"1027600621400","email":"ou88_director@76.fsin.gov.ru","hr-agency":false,"inn":"7603015360","kpp":"760301001","name":"ФКП ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ № 88","ogrn":"1027600621400","site":"https://76.fsin.gov.ru/professionalnoe-obrazovanie/professionalnoe-uchilishche-88/","url":"https://trudvsem.ru/company/1027600621400"},"creation-date":"2026-07-08","date_modify":"2026-08-17T13:02:52+0300","salary":"от 51700","salary_min":51700,"salary_max":55000,"job-name":"Преподаватель","vac_url":"https://trudvsem.ru/vacancy/card/1027600621400/6784addc-7aaf-11f1-96a1-71ec6ab38b2c","schedule":"Полный рабочий день","qualification":"не указано","requirements":"Высшее или среднее профессиональное образование по специальностям в области преподаваемых технических дисциплин. Обязательное уверенное владение ПК на уровне пользователя (Word,Excel). Ответственный, исполнительный, легкообучаемый, коммуникабельный

In [20]:
# конвертируем в словарь и смотрим ключи
dct_region = rqst.json()

dct_region.keys()
for key in dct_region.keys():
    print(f"Ключ <{key}>")
    print(dct_region.get(key))

Ключ <status>
200
Ключ <request>
{'api': 'v1'}
Ключ <meta>
{'total': 4113, 'limit': 100}
Ключ <results>

In [28]:
# смотрим ключи results
dct_region['results'].keys()

# смотрим содержимое vacancies
dct_region.get('results').get('vacancies')

# определяем тип данных
type(dct_region.get('results').get('vacancies'))

list

In [29]:
# исследуем первый элемент списка
dct_region.get('results').get('vacancies')[0]

{'vacancy': {'id': '9c787798-62fb-11f1-8685-7325a21cb113',
  'source': 'Вакансия работодателя',
  'region': {'region_code': '7600000000000', 'name': 'Ярославская область'},
  'company': {'companycode': '1207800166914',
   'email': 's.sokolov@t-ya.ru',
   'hr-agency': False,
   'inn': '7810909823',
   'kpp': '760401001',
   'name': 'ООО "ТРАНСПОРТ ЯРОСЛАВИИ"',
   'ogrn': '1207800166914',
   'site': 'i.fedulova@t-ya.ru',
   'url': 'https://trudvsem.ru/company/1207800166914'},
  'creation-date': '2026-06-08',
  'date_modify': '2026-08-17T13:12:28+0300',
  'salary': 'от 57487',
  'salary_min': 57487,
  'salary_max': 57487,
  'job-name': 'Слесарь по ремонту автомобилей',
  'vac_url': 'https://trudvsem.ru/vacancy/card/1207800166914/9c787798-62fb-11f1-8685-7325a21cb113',
  'employment': 'Полная занятость',
  'schedule': 'Полный рабочий день',
  'qualification': 'Среднее профессиональное образование',
  'requirements': 'опыт работы автослесарем; знание технического устройства автобуса умение работать с ручным инструментом, спец. инструментом',
  'duty': 'Проводить работы по ремонту автобусов, соблюдая технологические нормы по ремонту и техническому обслуживанию автобусов.',
  'category': {'specialisation': 'Транспорт, автобизнес, логистика, склад, ВЭД'},
  'requirement': {'education': 'Общее образование', 'experience': 1},
  'addresses': {'address': [{'location': 'Ярославская область, г Ярославль, Московский проспект, дом: Д. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;',
     'lng': '39.849535',
     'lat': '57.579638'}]},
  'social_protected': 'Инвалид',
  'contact_list': [{'contact_type': 'Телефон',
    'contact_value': '+7(910) 973-03-15'},
   {'contact_type': 'Мобильный телефон',
    'contact_value': '+7(910) 973-03-15'}],
  'contact_person': 'Ирина Анатольевна Федулова',
  'work_places': 1,
  'code_profession': '202115',
  'typicalPosition': 'Ничего не выбрано',
  'skills': [],
  'workPlaceType': {'workPlaceForeign': False,
   'workPlaceOrdinary': True,
   'workPlaceQuota': False,
   'workPlaceSocialProtected': ['Инвалид'],
   'workPlaceSpecial': False},
  'shift': [],
  'trainingDays': 0,
  'currency': '«руб.»'}}

In [31]:
# смотрим отдельную вакансию
lst_vac = dct_region.get('results').get('vacancies')
lst_vac[0]

{'vacancy': {'id': '9c787798-62fb-11f1-8685-7325a21cb113',
  'source': 'Вакансия работодателя',
  'region': {'region_code': '7600000000000', 'name': 'Ярославская область'},
  'company': {'companycode': '1207800166914',
   'email': 's.sokolov@t-ya.ru',
   'hr-agency': False,
   'inn': '7810909823',
   'kpp': '760401001',
   'name': 'ООО "ТРАНСПОРТ ЯРОСЛАВИИ"',
   'ogrn': '1207800166914',
   'site': 'i.fedulova@t-ya.ru',
   'url': 'https://trudvsem.ru/company/1207800166914'},
  'creation-date': '2026-06-08',
  'date_modify': '2026-08-17T13:12:28+0300',
  'salary': 'от 57487',
  'salary_min': 57487,
  'salary_max': 57487,
  'job-name': 'Слесарь по ремонту автомобилей',
  'vac_url': 'https://trudvsem.ru/vacancy/card/1207800166914/9c787798-62fb-11f1-8685-7325a21cb113',
  'employment': 'Полная занятость',
  'schedule': 'Полный рабочий день',
  'qualification': 'Среднее профессиональное образование',
  'requirements': 'опыт работы автослесарем; знание технического устройства автобуса умение работать с ручным инструментом, спец. инструментом',
  'duty': 'Проводить работы по ремонту автобусов, соблюдая технологические нормы по ремонту и техническому обслуживанию автобусов.',
  'category': {'specialisation': 'Транспорт, автобизнес, логистика, склад, ВЭД'},
  'requirement': {'education': 'Общее образование', 'experience': 1},
  'addresses': {'address': [{'location': 'Ярославская область, г Ярославль, Московский проспект, дом: Д. 112А;офис/квартира: ПОМЕЩ. 47,ЭТАЖ 3;',
     'lng': '39.849535',
     'lat': '57.579638'}]},
  'social_protected': 'Инвалид',
  'contact_list': [{'contact_type': 'Телефон',
    'contact_value': '+7(910) 973-03-15'},
   {'contact_type': 'Мобильный телефон',
    'contact_value': '+7(910) 973-03-15'}],
  'contact_person': 'Ирина Анатольевна Федулова',
  'work_places': 1,
  'code_profession': '202115',
  'typicalPosition': 'Ничего не выбрано',
  'skills': [],
  'workPlaceType': {'workPlaceForeign': False,
   'workPlaceOrdinary': True,
   'workPlaceQuota': False,
   'workPlaceSocialProtected': ['Инвалид'],
   'workPlaceSpecial': False},
  'shift': [],
  'trainingDays': 0,
  'currency': '«руб.»'}}

In [59]:
region_code = "76"
salary_level = 30000
# Список для сохранения всех найденных вакансий
results_list = []

for offset_number in tqdm(range(0, 10)):
    link = f"http://opendata.trudvsem.ru/api/v1/vacancies/region/{region_code}?offset={offset_number}"
    anws = requests.get(link)
    time.sleep(1)

    if anws.status_code == 200:
        dct_region = anws.json()

        results = dct_region.get("results") or {}
        lst_vac = results.get("vacancies") or []

        for vac in lst_vac:
            vacancy_data = vac.get("vacancy") or {}

            raw_salary = vacancy_data.get("salary", 0)
            try:
                salary = int(raw_salary) if raw_salary is not None else 0
            except (ValueError, TypeError):
                salary = 0

            if salary >= salary_level:
                company = vacancy_data.get("company") or {}

                addresses = vacancy_data.get("addresses") or {}
                address_list = addresses.get("address") or []
                location = (
                    address_list[0].get("location", "Адрес не указан")
                    if address_list
                    else "Адрес не указан"
                )

                # Создаем словарь под каждую вакансию
                dct_one_vac = {
                    "Название региона": vacancy_data.get("region", {}).get(
                        "name", "Название региона не указано"
                    ),
                    "Название компании": company.get(
                        "name", "Компания не указана"
                    ),
                    "Почта компании": company.get(
                        "email", "Почта не указана"
                    ),
                    "ИНН": company.get("inn", "ИНН не указан"),
                    "Вакансия": vacancy_data.get(
                        "job-name", "Название не указано"
                    ),
                    "Предлагаемая зарплата": salary,
                    "Обязанности": vacancy_data.get(
                        "duty", "Обязанности не указаны"
                    ),
                    "Адрес компании": location,
                }

                # Сохраняем словарь в общий список
                results_list.append(dct_one_vac)

100%|██████████| 10/10 [01:43<00:00, 10.32s/it]

In [60]:
# Превращаем результат в DataFrame
df = pd.DataFrame(results_list)

df.head()

Empty DataFrame
Columns: []
Index: []

**Задача 2. Web-scraping**

In [70]:
from bs4 import BeautifulSoup

In [63]:
# формируем запрос
page_number = 2
req = f'https://www.piter.com/collection/kompyutery-i-internet?page={page_number}'

In [64]:
# отправка запроса
anws = requests.get(req)

anws.status_code

200

In [67]:
# анализ ответа
anws.text

'  \n\n \n  \n<!DOCTYPE html>\n<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->\n    <head><meta data-config="{&quot;collection_products_count&quot;:598}" name="page-config" content="" /><meta data-config="{&quot;money_with_currency_format&quot;:{&quot;delimiter&quot;:&quot;&quot;,&quot;separator&quot;:&quot;.&quot;,&quot;format&quot;:&quot;%n %u&quot;,&quot;unit&quot;:&quot;р.&quot;,&quot;show_price_without_cents&quot;:0},&quot;currency_code&quot;:&quot;RUR&quot;,&quot;currency_iso_code&quot;:&quot;RUB&quot;,&quot;default_currency&quot;:{&quot;title&quot;:&quot;Российский рубль&quot;,&quot;code&quot;:&quot;RUR&quot;,&quot;rate&quot;:1.0,&quot;format_string&quot;:&quot;%n %u&quot;,&quot;unit&quot;:&quot;р.&quot;,&quot;price_separator&quot;:&quot;&quot;,&quot;is_default&quot;:true,&quot;price_delimiter&quot;:&quot;&quot;,&quot;show_price_with_delimiter&quot;:false,&quot;show_price_without_cents&quot;:false},&quot;facebook&quot;:{&quot;pixelActive&quot;:false,&quot;currency_code&quot;:&quot;RUB&quot;,&quot;use_variants&quot;:null},&quot;vk&quot;:{&quot;pixel_active&quot;:null,&quot;price_list_id&quot;:null},&quot;new_ya_metrika&quot;:true,&quot;ecommerce_data_container&quot;:&quot;dataLayer&quot;,&quot;common_js_version&quot;:null,&quot;vue_ui_version&quot;:null,&quot;feedback_captcha_enabled&quot;:&quot;1&quot;,&quot;account_id&quot;:73475,&quot;hide_items_out_of_stock&quot;:false,&quot;forbid_order_over_existing&quot;:true,&quot;minimum_items_price&quot;:null,&quot;enable_comparison&quot;:true,&quot;locale&quot;:&quot;ru&quot;,&quot;client_group&quot;:null,&quot;consent_to_personal_data&quot;:{&quot;active&quot;:true,&quot;obligatory&quot;:true,&quot;description&quot;:&quot;\\u003cp\\u003eНастоящим подтверждаю, что я ознакомлен и согласен с \\u003ca href=\\&quot;https://www.piter.com/page/ContractOfOffer\\&quot; target=\\&quot;blank\\&quot;\\u003eУсловиями продажи\\u003c/a\\u003e\\u003c/p\\u003e&quot;},&quot;yandex_captcha_key&quot;:&quot;ysc1_ec1ApqrRlTZTXotpTnO8PmXe2ISPHxsd9MO3y0rye822b9d2&quot;,&quot;checkout_float_order_content_block&quot;:false,&quot;available_products_characteristics_ids&quot;:null,&quot;sber_id_app_id&quot;:&quot;5b5a3c11-72e5-4871-8649-4cdbab3ba9a4&quot;,&quot;theme_generation&quot;:2,&quot;quick_checkout_captcha_enabled&quot;:false,&quot;max_order_lines_count&quot;:500,&quot;sber_bnpl_min_amount&quot;:1000,&quot;sber_bnpl_max_amount&quot;:50000,&quot;counter_settings&quot;:{&quot;data_layer_name&quot;:&quot;dataLayer&quot;,&quot;new_counters_setup&quot;:false,&quot;add_to_cart_event&quot;:true,&quot;remove_from_cart_event&quot;:true,&quot;add_to_wishlist_event&quot;:true},&quot;site_setting&quot;:{&quot;show_cart_button&quot;:true,&quot;show_service_button&quot;:false,&quot;show_marketplace_button&quot;:false,&quot;show_quick_checkout_button&quot;:false},&quot;warehouses&quot;:[{&quot;id&quot;:5677321,&quot;title&quot;:&quot;Склад&quot;,&quot;array_index&quot;:0}],&quot;captcha_type&quot;:&quot;yandex&quot;,&quot;human_readable_urls&quot;:false}" name="shop-config" content="" /><meta name=\'js-evnvironment\' content=\'production\' /><meta name=\'default-locale\' content=\'ru\' /><meta name=\'insales-redefined-api-methods\' content="[]" /><script src="/packs/js/shop_bundle-a5f034353f50f3bc5e7d.js"></script><script type="text/javascript" src="https://cdn.insales-shop.ru/assets/static-versioned/v3.72/static/libs/lodash/4.17.21/lodash.min.js"></script>\n<!--InsalesCounter -->\n<script type="text/javascript">\n(function() {\n  if (typeof window.__insalesCounterId !== \'undefined\') {\n    return;\n  }\n\n  try {\n    Object.defineProperty(window, \'__insalesCounterId\', {\n      value: 73475,\n      writable: true,\n      configurable: true\n    });\n  } catch (e) {\n    console.error(\'InsalesCounter: Failed to define property, using fallback:\', e);\n    window.__insalesCounterId = 73475;\n  }\n\n  if (typeof window.__insalesCounterId === \'undefined\') {\n    console.error(\'InsalesCounter: Failed to set counter ID\');\n    return;\n  }\n\n  let script = document.createElement(\'script\');\n  script.async = true;\n  script.src = \'/javascripts/insales_counter.js?7\';\n  let firstScript = document.getElementsByTagName(\'script\')[0];\n  firstScript.parentNode.insertBefore(script, firstScript);\n})();\n</script>\n<!-- /InsalesCounter -->\n    <script type="text/javascript">\n      (function() {\n        var fileref = document.createElement(\'script\');\n        fileref.setAttribute("type","text/javascript");\n        fileref.setAttribute("src", \'https://pnn.insales-tech.ru/pnn/pnn.js\');\n        document.getElementsByTagName("head")[0].appendChild(fileref);\n      })();\n    </script>\n\n    <script type="text/javascript">\n      (function() {\n        window.__rees_shop_id = "dc1ae98f18773f0128cb86ef284fe7";\nvar fileref = document.createElement(\'link\'); \nfileref.setAttribute(\'rel\',\'preload\'); \nfileref.setAttribute(\'href\', \'//cdn.rees46.ru/insales.min.js\'); \nfileref.setAttribute(\'as\', \'script\'); \ndocument.getElementsByTagName(\'head\')[0].appendChild(fileref);\nfileref = document.createElement(\'script\'); \nfileref.setAttribute(\'type\',\'text/javascript\'); \nfileref.setAttribute(\'src\', \'//cdn.rees46.ru/insales.min.js\'); \nfileref.setAttribute(\'async\', \'true\'); \ndocument.getElementsByTagName(\'head\')[0].appendChild(fileref);\nwindow.r46_app_installation_date = "2026-08-12 04:58:57 UTC";\nwindow.r46=window.r46||function(){(r46.q=r46.q||[]).push(arguments)};\n\n      })();\n    </script>\n\n        <meta property="og:title" content="КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА,">\n        <meta property="og:site_name" content="www.piter.com">\n        \n      \t\n     \t\t\t<meta property="og:image" content="https://cdn.insales-shop.ru/images/collections/1/3232/1043616/cat4.png"/>\n\t\t\t\n        <meta charset="utf-8">\n        <meta http-equiv="X-UA-Compatible" content="IE=edge">\n        <title>КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА,</title>\n        <meta name="description" content="КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА, заказать, заказ, купить, цена, онлайн, стоимость, интернет магазин, каталог">\n      \t<meta name="keywords" content="КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА , литература по компьютерам,самоучители, Windows">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n      \t<meta name="mailru-verification" content="10f3cc79957ca1ae" />\n      \t<meta name="yandex-verification" content="c39ebc28d4b5c8e3" />\n        \n\n      \t\n      \n<meta name="google-site-verification" content="OyipTZeM7aoWKWQHDFeBh77pZEBLNul_HQGRcCd_ujE" />      \n<meta name="google-site-verification" content="Zc3Em4GpLp8ar9C9dxLMRr4ozQ2HgAnexhxU_vqnXoc" />\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<!--\n<script async src="https://www.googletagmanager.com/gtag/js?id=UA-73201331-1"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'UA-73201331-1\');\n</script>-->\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<!--\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-MJLC7C868B"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'G-MJLC7C868B\');\n</script>      \n-->\n<script type="text/javascript" src="https://cdn.insales-shop.ru/assets/common-js/common.v2.27.6.js"></script>\n <!-- Yandex.Metrika counter -->\n<script type="text/javascript" >\n   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};\n   m[i].l=1*new Date();\n   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}\n   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})\n   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");\n\n   ym(97806036, "init", {\n        clickmap:true,\n        trackLinks:true,\n        accurateTrackBounce:true\n      \n   });\n   ym(97805040, "init", {\n        clickmap:true,\n        trackLinks:true,\n        accurateTrackBounce:true,\n        webvisor: true\n   });\n</script>\n<noscript>\n  <div>\n    <img src="https://mc.yandex.ru/watch/97806036" style="position:absolute; left:-9999px;" alt="" />\n    <img src="https://mc.yandex.ru/watch/97805040" style="position:absolute; left:-9999px;" alt="" />\n  </div>\n</noscript>\n\n<!-- /Yandex.Metrika counter -->     \n      <!-- Google Tag Manager -->\n      <!--\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-WP288D5\');</script>-->\n<!-- End Google Tag Manager -->\n\n       \t<link rel="icon" type="image/vnd.microsoft.icon" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/favicon.ico" />\n\t\t<link rel="shortcut icon" type="image/x-icon" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/favicon.ico" />\n \t\t<link rel="image_src" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/piter_logo_socnet.jpg">\n        <link rel="stylesheet" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/normalize.css">\n        <link rel="stylesheet" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/style.css">\n        <link rel="stylesheet" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/font.css">\n        <link rel="stylesheet" href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/alertify.css">\n       <script src="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/alertify.min.js"></script>\n        <script src="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/modernizr-2.6.2.min.js"></script>\n    \t<script type="text/javascript">\n       \t\tvar rrPartnerId = "51c80f5d0d422d227c73e1a5";       \n       \t\tvar rrApi = {}; \n       \t\tvar rrApiOnReady = rrApiOnReady || [];\n       \t\trrApi.addToBasket = rrApi.order = rrApi.categoryView = rrApi.view = \n           \trrApi.recomMouseDown = rrApi.recomAddToCart = function() {};\n       \t\t(function(d) \n             \t{\n           \t\tvar ref = d.getElementsByTagName(\'script\')[0];\n           \t\tvar apiJs, apiJsId = \'rrApi-jssdk\';\n           \t\tif (d.getElementById(apiJsId)) return;\n           \t\tapiJs = d.createElement(\'script\');\n           \t\tapiJs.id = apiJsId;\n           \t\tapiJs.async = true;\n           \t\tapiJs.src = "//cdn.retailrocket.ru/content/javascript/tracking.js";\n           \t\tref.parentNode.insertBefore(apiJs, ref);\n       \t\t\t}(document));\n    </script>  \n\n\t\n\t \n\t\n<!-- REES46 get current currency begin -->\n<script type="text/javascript">\n    window.r46_currency=\'0 р.\';\n</script>\n<!-- REES46 get current currency end -->\n<!-- REES46 tracking scripts -->\n<script type="text/javascript">\nwindow.r46_variant = true;\nwindow.r46_currency=\'0 р.\';\n\nwindow.r46_category_id = 1572454;\n\n\n</script>\n<!-- /REES46 tracking scripts -->\n      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />\n      <script src="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/fancybox_3.5.7.min.js"></script>\n\n\n<!-- GdeSlon START -->\n<script type = "text/javascript" >\r\n    if (!window.gdeslon_q || window.gdeslon_q instanceof Array) {\r\n        var hasPerformance = "undefined" !== typeof performance && "function" === typeof performance.now;\r\n        var perf = hasPerformance ? performance.now() : null;\r\n        var oldQueue = window.gdeslon_q || [];\r\n        window.gdeslon_q = function() {\r\n            var _exceptions = [],\r\n                _state = {},\r\n                appendScript = function(url) {\r\n                    var gss = document.createElement("script");\r\n                    gss.type = "text/javascript";\r\n                    gss.async = true;\r\n                    gss.src = url;\r\n                    var s = document.getElementsByTagName("script")[0];\r\n                    s.parentNode.insertBefore(gss, s)\r\n                },\r\n                serializeObject = function(obj) {\r\n                    return Object.keys(obj).map(function(key) {\r\n                        return encodeURIComponent(key) + "=" + encodeURIComponent(obj[key])\r\n                    }).join("&")\r\n                },\r\n                deserializeObject = function(str, pairsSeparator, keyValueSeparator) {\r\n                    var result = {},\r\n                        pairs, pair, key, value, i, l;\r\n                    if (!keyValueSeparator) {\r\n                        keyValueSeparator = "="\r\n                    }\r\n                    if (!str) {\r\n                        return result\r\n                    }\r\n                    pairs = str.split(pairsSeparator);\r\n                    for (i = 0, l = pairs.length; i < l; i++) {\r\n                        pair = pairs[i].replace(/^\\s+|\\s+$/g, "").split(keyValueSeparator);\r\n                        try {\r\n                            key = decodeURIComponent(pair[0]);\r\n                            value = decodeURIComponent(pair[1]);\r\n                            result[key] = value\r\n                        } catch (e) {\r\n                            console.log(e.message)\r\n                        }\r\n                    }\r\n                    return result\r\n                },\r\n                location = function() {\r\n                    return document.location\r\n                }(),\r\n                domain = function() {\r\n                    var domain = location.hostname || location.host.split(":")[0];\r\n                    var domainParts = domain.split(".");\r\n                    var l = domainParts.length;\r\n                    if (l > 1) {\r\n                        domain = domainParts[l - 2] + "." + domainParts[l - 1]\r\n                    }\r\n                    return domain\r\n                }(),\r\n                queryParams = function() {\r\n                    return deserializeObject(location.search.slice(1), "&")\r\n                }(),\r\n                cookieTtl = function() {\r\n                    var cookieTtl = parseInt(queryParams._gs_cttl, 10);\r\n                    if (!cookieTtl || isNaN(cookieTtl)) {\r\n                        cookieTtl = 180\r\n                    }\r\n                    return cookieTtl\r\n                }(),\r\n                writeCookie = function(name, value, ttlSeconds) {\r\n                    if (!(name && value)) {\r\n                        return\r\n                    }\r\n                    value = encodeURIComponent(value);\r\n                    var ttl = ttlSeconds || cookieTtl * 24 * 60 * 60;\r\n                    var date = new Date;\r\n                    date.setTime(date.getTime() + ttl * 1e3);\r\n                    var expires = "; expires=" + date.toUTCString();\r\n                    var domainParam = "domain=" + domain + "; ";\r\n                    document.cookie = name + "=" + value + expires + "; " + domainParam + "path=/;"\r\n                },\r\n                cookies = function(key) {\r\n                    return deserializeObject(document.cookie, ";")[key]\r\n                },\r\n                token = function() {\r\n                    return cookies("gdeslon.ru.__arc_token")\r\n                },\r\n                affiliate_id = function() {\r\n                    return cookies("gdeslon.ru.__arc_aid")\r\n                },\r\n                track_domain = function() {\r\n                    return cookies("gdeslon.ru.__arc_domain") || "gdeslon.ru"\r\n                },\r\n                pixel_domain = function() {\r\n                    return cookies("gdeslon.ru.__arc_gsp_domain") || "gdeslon.ru"\r\n                },\r\n                gs_uid = function() {\r\n                    return cookies("gdeslon.ru.user_id")\r\n                },\r\n                processor = function() {\r\n                    _state.pushStartedAt = Date.now();\r\n                    var pixel = [];\r\n                    var track = [];\r\n                    if (arguments.length === 0) {\r\n                        return\r\n                    }\r\n                    var obj = arguments[0];\r\n                    var shouldInvokeTrack = false;\r\n                    Object.keys(obj).forEach(function(key) {\r\n                        var val = obj[key];\r\n                        var same = "";\r\n                        switch (key) {\r\n                            case "page_type":\r\n                                pixel.mode = val;\r\n                                break;\r\n                            case "merchant_id":\r\n                                pixel.mid = val;\r\n                                track.merchant_id = val;\r\n                                break;\r\n                            case "category_id":\r\n                                pixel.cat_id = val;\r\n                                track.cat_id = val;\r\n                                break;\r\n                            case "products":\r\n                                if (!val || val.constructor !== Array) break;\r\n                                same = val.map(function(l) {\r\n                                    var repeats = [];\r\n                                    for (var i = 0; i < parseFloat(l.quantity); i++) {\r\n                                        repeats.push(l.id + ":" + parseFloat(l.price))\r\n                                    }\r\n                                    return repeats.join(",")\r\n                                });\r\n                                pixel.codes = same;\r\n                                track.codes = same;\r\n                                break;\r\n                            case "user_id":\r\n                                pixel.muid = val;\r\n                                track.muid = val;\r\n                                break;\r\n                            default:\r\n                                pixel[key] = val;\r\n                                track[key] = val;\r\n                                break\r\n                        }\r\n                    });\r\n                    if (obj.page_type === "thanks") {\r\n                        if (obj.hasOwnProperty("deduplication")) {\r\n                            if (Object.prototype.toString.call(obj.deduplication) === "[object String]") {\r\n                                var trueArr = ["gdeslon_cpa", "gdeslon", "gde slon", "", "undefined", "null", "true", "1"];\r\n                                shouldInvokeTrack = trueArr.indexOf(obj.deduplication.toLowerCase()) > -1\r\n                            } else {\r\n                                shouldInvokeTrack = true\r\n                            }\r\n                        } else {\r\n                            shouldInvokeTrack = true\r\n                        }\r\n                    }\r\n                    pixel.perf = parseInt(perf, 10);\r\n                    track.perf = pixel.perf;\r\n                    pixel.gs_uid = gs_uid();\r\n                    track.gs_uid = pixel.gs_uid;\r\n                    pixel._t = Date.now();\r\n                    track._t = Date.now();\r\n                    pixel.source = window.location.href;\r\n                    var url = "//" + pixel_domain() + "/gsp.js?" +

In [71]:
# разбор ответа
soup = BeautifulSoup(anws.text, 'lxml')
soup

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]--><!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]--><!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]--><!--[if gt IE 8]><!--><html class="no-js"> <!--<![endif]-->
<head><meta content="" data-config='{"collection_products_count":598}' name="page-config"/><meta content="" data-config='{"money_with_currency_format":{"delimiter":"","separator":".","format":"%n %u","unit":"р.","show_price_without_cents":0},"currency_code":"RUR","currency_iso_code":"RUB","default_currency":{"title":"Российский рубль","code":"RUR","rate":1.0,"format_string":"%n %u","unit":"р.","price_separator":"","is_default":true,"price_delimiter":"","show_price_with_delimiter":false,"show_price_without_cents":false},"facebook":{"pixelActive":false,"currency_code":"RUB","use_variants":null},"vk":{"pixel_active":null,"price_list_id":null},"new_ya_metrika":true,"ecommerce_data_container":"dataLayer","common_js_version":null,"vue_ui_version":null,"feedback_captcha_enabled":"1","account_id":73475,"hide_items_out_of_stock":false,"forbid_order_over_existing":true,"minimum_items_price":null,"enable_comparison":true,"locale":"ru","client_group":null,"consent_to_personal_data":{"active":true,"obligatory":true,"description":"\u003cp\u003eНастоящим подтверждаю, что я ознакомлен и согласен с \u003ca href=\"https://www.piter.com/page/ContractOfOffer\" target=\"blank\"\u003eУсловиями продажи\u003c/a\u003e\u003c/p\u003e"},"yandex_captcha_key":"ysc1_ec1ApqrRlTZTXotpTnO8PmXe2ISPHxsd9MO3y0rye822b9d2","checkout_float_order_content_block":false,"available_products_characteristics_ids":null,"sber_id_app_id":"5b5a3c11-72e5-4871-8649-4cdbab3ba9a4","theme_generation":2,"quick_checkout_captcha_enabled":false,"max_order_lines_count":500,"sber_bnpl_min_amount":1000,"sber_bnpl_max_amount":50000,"counter_settings":{"data_layer_name":"dataLayer","new_counters_setup":false,"add_to_cart_event":true,"remove_from_cart_event":true,"add_to_wishlist_event":true},"site_setting":{"show_cart_button":true,"show_service_button":false,"show_marketplace_button":false,"show_quick_checkout_button":false},"warehouses":[{"id":5677321,"title":"Склад","array_index":0}],"captcha_type":"yandex","human_readable_urls":false}' name="shop-config"/><meta content="production" name="js-evnvironment"/><meta content="ru" name="default-locale"/><meta content="[]" name="insales-redefined-api-methods"/><script src="/packs/js/shop_bundle-a5f034353f50f3bc5e7d.js"></script><script src="https://cdn.insales-shop.ru/assets/static-versioned/v3.72/static/libs/lodash/4.17.21/lodash.min.js" type="text/javascript"></script>
<!--InsalesCounter -->
<script type="text/javascript">
(function() {
  if (typeof window.__insalesCounterId !== 'undefined') {
    return;
  }

  try {
    Object.defineProperty(window, '__insalesCounterId', {
      value: 73475,
      writable: true,
      configurable: true
    });
  } catch (e) {
    console.error('InsalesCounter: Failed to define property, using fallback:', e);
    window.__insalesCounterId = 73475;
  }

  if (typeof window.__insalesCounterId === 'undefined') {
    console.error('InsalesCounter: Failed to set counter ID');
    return;
  }

  let script = document.createElement('script');
  script.async = true;
  script.src = '/javascripts/insales_counter.js?7';
  let firstScript = document.getElementsByTagName('script')[0];
  firstScript.parentNode.insertBefore(script, firstScript);
})();
</script>
<!-- /InsalesCounter -->
<script type="text/javascript">
      (function() {
        var fileref = document.createElement('script');
        fileref.setAttribute("type","text/javascript");
        fileref.setAttribute("src", 'https://pnn.insales-tech.ru/pnn/pnn.js');
        document.getElementsByTagName("head")[0].appendChild(fileref);
      })();
    </script>
<script type="text/javascript">
      (function() {
        window.__rees_shop_id = "dc1ae98f18773f0128cb86ef284fe7";
var fileref = document.createElement('link');
fileref.setAttribute('rel','preload');
fileref.setAttribute('href', '//cdn.rees46.ru/insales.min.js');
fileref.setAttribute('as', 'script');
document.getElementsByTagName('head')[0].appendChild(fileref);
fileref = document.createElement('script');
fileref.setAttribute('type','text/javascript');
fileref.setAttribute('src', '//cdn.rees46.ru/insales.min.js');
fileref.setAttribute('async', 'true');
document.getElementsByTagName('head')[0].appendChild(fileref);
window.r46_app_installation_date = "2026-08-12 04:58:57 UTC";
window.r46=window.r46||function(){(r46.q=r46.q||[]).push(arguments)};

      })();
    </script>
<meta content="КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА," property="og:title"/>
<meta content="www.piter.com" property="og:site_name"/>
<meta content="https://cdn.insales-shop.ru/images/collections/1/3232/1043616/cat4.png" property="og:image"/>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<title>КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА,</title>
<meta content="КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА, заказать, заказ, купить, цена, онлайн, стоимость, интернет магазин, каталог" name="description"/>
<meta content="КОМПЬЮТЕРНАЯ ЛИТЕРАТУРА , литература по компьютерам,самоучители, Windows" name="keywords"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="10f3cc79957ca1ae" name="mailru-verification"/>
<meta content="c39ebc28d4b5c8e3" name="yandex-verification"/>
<meta content="OyipTZeM7aoWKWQHDFeBh77pZEBLNul_HQGRcCd_ujE" name="google-site-verification"/>
<meta content="Zc3Em4GpLp8ar9C9dxLMRr4ozQ2HgAnexhxU_vqnXoc" name="google-site-verification"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<!--
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-73201331-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-73201331-1');
</script>-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<!--
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MJLC7C868B"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MJLC7C868B');
</script>
-->
<script src="https://cdn.insales-shop.ru/assets/common-js/common.v2.27.6.js" type="text/javascript"></script>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();
   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(97806036, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true

   });
   ym(97805040, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor: true
   });
</script>
<noscript>
<div>
<img alt="" src="https://mc.yandex.ru/watch/97806036" style="position:absolute; left:-9999px;"/>
<img alt="" src="https://mc.yandex.ru/watch/97805040" style="position:absolute; left:-9999px;"/>
</div>
</noscript>
<!-- /Yandex.Metrika counter -->
<!-- Google Tag Manager -->
<!--
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WP288D5');</script>-->
<!-- End Google Tag Manager -->
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/piter_logo_socnet.jpg" rel="image_src"/>
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/normalize.css" rel="stylesheet"/>
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/style.css" rel="stylesheet"/>
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/font.css" rel="stylesheet"/>
<link href="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/alertify.css" rel="stylesheet"/>
<script src="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/alertify.min.js"></script>
<script src="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/modernizr-2.6.2.min.js"></script>
<script type="text/javascript">
       		var rrPartnerId = "51c80f5d0d422d227c73e1a5";
       		var rrApi = {};
       		var rrApiOnReady = rrApiOnReady || [];
       		rrApi.addToBasket = rrApi.order = rrApi.categoryView = rrApi.view =
           	rrApi.recomMouseDown = rrApi.recomAddToCart = function() {};
       		(function(d)
             	{
           		var ref = d.getElementsByTagName('script')[0];
           		var apiJs, apiJsId = 'rrApi-jssdk';
           		if (d.getElementById(apiJsId)) return;
           		apiJs = d.createElement('script');
           		apiJs.id = apiJsId;
           		apiJs.async = true;
           		apiJs.src = "//cdn.retailrocket.ru/content/javascript/tracking.js";
           		ref.parentNode.insertBefore(apiJs, ref);
       			}(document));
    </script>
<!-- REES46 get current currency begin -->
<script type="text/javascript">
    window.r46_currency='0 р.';
</script>
<!-- REES46 get current currency end -->
<!-- REES46 tracking scripts -->
<script type="text/javascript">
window.r46_variant = true;
window.r46_currency='0 р.';

window.r46_category_id = 1572454;


</script>
<!-- /REES46 tracking scripts -->
<link href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" rel="stylesheet"/>
<script src="https://cdn.insales-shop.ru/assets/1/4689/1938001/1785495863/fancybox_3.5.7.min.js"></script>
<!-- GdeSlon START -->
<script type="text/javascript">
    if (!window.gdeslon_q || window.gdeslon_q instanceof Array) {
        var hasPerformance = "undefined" !== typeof performance && "function" === typeof performance.now;
        var perf = hasPerformance ? performance.now() : null;
        var oldQueue = window.gdeslon_q || [];
        window.gdeslon_q = function() {
            var _exceptions = [],
                _state = {},
                appendScript = function(url) {
                    var gss = document.createElement("script");
                    gss.type = "text/javascript";
                    gss.async = true;
                    gss.src = url;
                    var s = document.getElementsByTagName("script")[0];
                    s.parentNode.insertBefore(gss, s)
                },
                serializeObject = function(obj) {
                    return Object.keys(obj).map(function(key) {
                        return encodeURIComponent(key) + "=" + encodeURIComponent(obj[key])
                    }).join("&")
                },
                deserializeObject = function(str, pairsSeparator, keyValueSeparator) {
                    var result = {},
                        pairs, pair, key, value, i, l;
                    if (!keyValueSeparator) {
                        keyValueSeparator = "="
                    }
                    if (!str) {
                        return result
                    }
                    pairs = str.split(pairsSeparator);
                    for (i = 0, l = pairs.length; i < l; i++) {
                        pair = pairs[i].replace(/^\s+|\s+$/g, "").split(keyValueSeparator);
                        try {
                            key = decodeURIComponent(pair[0]);
                            value = decodeURIComponent(pair[1]);
                            result[key] = value
                        } catch (e) {
                            console.log(e.message)
                        }
                    }
                    return result
                },
                location = function() {
                    return document.location
                }(),
                domain = function() {
                    var domain = location.hostname || location.host.split(":")[0];
                    var domainParts = domain.split(".");
                    var l = domainParts.length;
                    if (l > 1) {
                        domain = domainParts[l - 2] + "." + domainParts[l - 1]
                    }
                    return domain
                }(),
                queryParams = function() {
                    return deserializeObject(location.search.slice(1), "&")
                }(),
                cookieTtl = function() {
                    var cookieTtl = parseInt(queryParams._gs_cttl, 10);
                    if (!cookieTtl || isNaN(cookieTtl)) {
                        cookieTtl = 180
                    }
                    return cookieTtl
                }(),
                writeCookie = function(name, value, ttlSeconds) {
                    if (!(name && value)) {
                        return
                    }
                    value = encodeURIComponent(value);
                    var ttl = ttlSeconds || cookieTtl * 24 * 60 * 60;
                    var date = new Date;
                    date.setTime(date.getTime() + ttl * 1e3);
                    var expires = "; expires=" + date.toUTCString();
                    var domainParam = "domain=" + domain + "; ";
                    document.cookie = name + "=" + value + expires + "; " + domainParam + "path=/;"
                },
                cookies = function(key) {
                    return deserializeObject(document.cookie, ";")[key]
                },
                token = function() {
                    return cookies("gdeslon.ru.__arc_token")
                },
                affiliate_id = function() {
                    return cookies("gdeslon.ru.__arc_aid")
                },
                track_domain = function() {
                    return cookies("gdeslon.ru.__arc_domain") || "gdeslon.ru"
                },
                pixel_domain = function() {
                    return cookies("gdeslon.ru.__arc_gsp_domain") || "gdeslon.ru"
                },
                gs_uid = function() {
                    return cookies("gdeslon.ru.user_id")
                },
                processor = function() {
                    _state.pushStartedAt = Date.now();
                    var pixel = [];
                    var track = [];
                    if (arguments.length === 0) {
                        return
                    }
                    var obj = arguments[0];
                    var shouldInvokeTrack = false;
                    Object.keys(obj).forEach(function(key) {
                        var val = obj[key];
                        var same = "";
                        switch (key) {
                            case "page_type":
                                pixel.mode = val;
                                break;
                            case "merchant_id":
                                pixel.mid = val;
                                track.merchant_id = val;
                                break;
                            case "category_id":
                                pixel.cat_id = val;
                                track.cat_id = val;
                                break;
                            case "products":
                                if (!val || val.constructor !== Array) break;
                                same = val.map(function(l) {
                                    var repeats = [];
                                    for (var i = 0; i < parseFloat(l.quantity); i++) {
                                        repeats.push(l.id + ":" + parseFloat(l.price))
                                    }
                                    return repeats.join(",")
                                });
                                pixel.codes = same;
                                track.codes = same;
                                break;
                            case "user_id":
                                pixel.muid = val;
                                track.muid = val;
                                break;
                            default:
                                pixel[key] = val;
                                track[key] = val;
                                break
                        }
                    });
                    if (obj.page_type === "thanks") {
                        if (obj.hasOwnProperty("deduplication")) {
                            if (Object.prototype.toString.call(obj.deduplication) === "[object String]") {
                                var trueArr = ["gdeslon_cpa", "gdeslon", "gde slon", "", "undefined", "null", "true", "1"];
                                shouldInvokeTrack = trueArr.indexOf(obj.deduplication.toLowerCase()) > -1
                            } else {
                                shouldInvokeTrack = true
                            }
                        } else {
                            shouldInvokeTrack = true
                        }
                    }
                    pixel.perf = parseInt(perf, 10);
                    track.perf = pixel.perf;
                    pixel.gs_uid = gs_uid();
                    track.gs_uid = pixel.gs_uid;
                    pixel._t = Date.now();
                    track._t = Date.now();
                    pixel.source = window.location.href;
                    var url = "//" + pixel_domain() + "/gsp.js?" + serializeObject(pixel);
                    appendScript(url);
                    if (shouldInvokeTrack) {
                        _state.shouldInvokeTrack = true;
                        track.affiliate_id = affiliate_id();
                        track.token = token();
                        url = "//" + track_domain() + "/purchase.js?" + serializeObject(track);
                        appendScript(url)
                    } else {
                        _state.shouldInvokeTrack = false
                    }
                    _state.pushFinishedAt = Date.now()
                },
                _push = function() {
                    try {
                        return processor.apply(null, arguments)
                    } catch (c) {
                        _exceptions.push(c);
                        var url = "https://gdeslon.ru/error.js?" + serializeObject({
                            message: c.message
                        });
                        appendScript(url)
                    }
                };
            if (queryParams.gsaid) {
                writeCookie("gdeslon.ru.__arc_aid", queryParams.gsaid)
            }
            if (queryParams._gs_ref) {
                writeCookie("gdeslon.ru.__arc_token", queryParams._gs_ref)
            }
            if (queryParams._gs_vm) {
                writeCookie("gdeslon.ru.__arc_domain", queryParams._gs_vm)
            }
            if (queryParams._gs_ld) {
                writeCookie("gdeslon.ru.__arc_gsp_domain", queryParams._gs_ld)
            }
            return {
                push: _push,
                exceptions: _exceptions,
                state: _state
            }
        }();
        window.gdeslon_q.push.apply(null, oldQueue)
    }

  const queryStringC = window.location.search;
  const urlParamsC = new URLSearchParams(queryStringC);
  const utmSrcC = urlParamsC.get('utm_source');
  if (utmSrcC!=null)
  {
    document.cookie = "utm_source_adv="+utmSrcC+"; path=/;";
  }



</script>
<script>
window.gdeslon_q = window.gdeslon_q || [];

In [74]:
# исследование страницы
results = soup.find_all('div',
                        attrs={'class': ['grid-3 prod-block book-block clear-class2 clear-class4',
                                         'grid-3 prod-block book-block',
                                         'grid-3 prod-block book-block clear-class2']})
len(results)

12

In [76]:
# сбор данных
dct_book = {'Автор': None,
            'Название': None,
            'Ссылка': None}
lst_books = []

for book in results:
    dct_book['Автор'] = (
                                book.find('span',
                                          attrs={'class': 'author'})
                                    .get_text(strip=True)
                                )
    dct_book['Название'] = (
                                book.find('span',
                                          attrs={'class': 'title'})
                                    .get_text(strip=True)
                                  )
    dct_book['Ссылка'] = (
                     'https://www.piter.com' + book.find('a').get('href')
                         )
    lst_books.append(dct_book.copy())

In [77]:
pd.DataFrame(lst_books)

,Автор,Название,Ссылка
0,Клеппман М.,Высоконагруженные приложения. Программирование...,https://www.piter.com/collection/kompyutery-i-...
1,Дыновски Л.,Стили API. Проектирование и внедрение,https://www.piter.com/collection/kompyutery-i-...
2,Дауни А.,Думай как аналитик. Статистика и данные с прим...,https://www.piter.com/collection/kompyutery-i-...
3,Нвайву И.,Автоматизация доставки API. Улучшаем скорость ...,https://www.piter.com/collection/kompyutery-i-...
4,Брикман Е.,Основы DevOps и Software Delivery. Практика ра...,https://www.piter.com/collection/kompyutery-i-...
5,Райс Л.,Безопасность контейнеров. Фундаментальный подх...,https://www.piter.com/collection/kompyutery-i-...
6,Труммер И.,"Анализ данных с LLM. Текст, таблицы, изображен...",https://www.piter.com/collection/kompyutery-i-...
7,Олифер В. Г.,"Компьютерные сети. Принципы, технологии, прото...",https://www.piter.com/collection/kompyutery-i-...
8,Рахман А.,Современный Java Concurrency. Глубокое погруже...,https://www.piter.com/collection/kompyutery-i-...
9,Мадаппарамбат Г.,Kubernetes. Полное руководство по развертывани...,https://www.piter.com/collection/kompyutery-i-...
10,Стиллмен Э.,Head First. Изучаем C# и .NET. 5-е изд.,https://www.piter.com/collection/kompyutery-i-...
11,Виво М.,System Design. Проектирование мобильных систем...,https://www.piter.com/collection/kompyutery-i-...